### ISSUE TITLE
Product "Cost Price" Overwritten

### ISSUE THREAD

**Issue by hpowermach** [openlabs/magento_integration#138]
I spent many hours setting the product "Cost Price" in OpenERP, only to have it all overwritten by the connector. The connector is setting the product "Cost Price" the same as the "Sell Price", and thus the generated purchase orders all have the wrong price.

I suggest two things:

1) Have an option for the connector to ignore the "Cost Price" field.

2) Have the connector take the value from a custom Magento field. Though I'm not sure how this will impact average costing if set.

I looked through all the issues here and didn't see this issue mentioned, which is surprising. Did I miss something?

Thanks for the great work!

**Comment by capitaine** [comment]
I think most users do their purchases with openERP. So the "cost price" should be calculated inside openerp on the basis of the suppliers' invoices and then be available to export to Magento (e.g. while updating stock), rather than importing it from Magento to openERP. This should be optional in openerp->Mage process because this way "cost price" is useless in magento for openerp users, and also for those who for some reason wish to import "cost price" from magento, they should have an option available in Mage->openerp process.

**Comment by thatompeta** [comment]
Hi,

I am one of the people that maintains catalog in the store and needs to import updated cost price from Magento. How do I go about that.I also get error everytime I udate catalog.
