### ISSUE TITLE
Products Imported, but Inventory Not Updating

### ISSUE THREAD

**Issue by l-arnold** [openlabs/magento_integration#158]
At some point I ran a "Export Inventory" from Magento_Integration and all Magento inventory became Zero (0).

Now however, I can only update inventory in Magento.  OpenERP shows Zero after "Import Catalog" and even after upating inventory in OpenERP (as Admin is the only access route) updated inventory is not making it into Magento.

As a fall back it wouuld seem appropriate that Magento Inventory go into OpenERP but that is not happening either (I understand that accounting/erp would prefer inventory being recieved from PO, Build or Warehouse action rather than arbitrary entry, but No can Transfer right now.

**Comment by l-arnold** [comment]
Initially a "single product update" was relateively fast (though ineffective).  Now it is taking as long as "import catalog".  I also worry that Categories are not mapping as I have an accumulating number of items in "Unclassified Magento Products".  

Strangely I can get to these products as a group under "Warehouse/Products" then choose filter "group by category".  They are not showing up in Products by Category (directly above in Warehouse Actions Bar), though this is an OPENERP issue, wanting a Top Level Category to have SubCategories to view.  Root Category and All Products are on the same level.

It is looking like I will need to abandon this effort soon.  Generally 30 Minutes to complete (with out visible updates) any sort of update action in the Module.

Bummer.

**Comment by shalabhaggarwal** [comment]
@l-arnold I agree that update from either side takes time. This directly depends on the number of records being synced. We ourselves are looking for ways to implement pagination to make things faster.

As far as the products going under "Unclassified Magento Products" is concerned, this can be because those categories are not imported yet. For this you can always run "Import Catalog" and that should import categories and put any new imported products under right categories. Also you can always change the category on ERP to put the product in right one.

Single product update does not update the stock.

We dont import stock from magento. We only export the stock from OpenERP to Magento for obvious reasons. If the stock is not getting imported, please check that the manage stock is allowed on the product in magento. If there are any stack traces being generated, please put them up too.

Thanks for your efforts with the connector. We appreciate your help.

**Comment by l-arnold** [comment]
Manage Stock is always checked.  Magento starts with stock.  OpenERP does not land with stock.  

There is some, to me, difficult logic in that Magento has  to first create the product. In OpenERP, after bringing a product in, you cannot "duplicate" a product (to create a new one), but you should update the inventory in OpenERP and write back to Magento.  Essentially the work has to be done on Magento, then a small change (perhaps descriptions also can be changed) then write back to Magento.

Ideally there would be bi-directional synch.  Other comments on other threads follow.
