### ISSUE TITLE
Update products from openerp to magento

### ISSUE THREAD

**Issue by pradeepnew** [openlabs/magento_integration#159]
I am using update catalog button to update magento to openerp.

But there is no option to update the product from openerp to magento.

**Comment by shalabhaggarwal** [comment]
Not sure if we have a plan to do this.

But we can leave this issue open in case this needs to be implemented in future.

**Comment by l-arnold** [comment]
Seems would be doable if inventory levels are updated, would seem that text fields could be updated.  That said, I am not writing the code and do not, at present, have an install to test on.  Thank you for your efforts.

**Comment by sharoonthomas** [comment]
This is not a goal of the connector because:
1. Magento admin panel is a pretty sophisticated system which has a lot of options, which are further enhanced by its ecosystem of addons.
2. To be able to update the information on magento, OpenERP would need to have all of this information too (atleast most of it). This would be duplicating the functionality of magento on OpenERP.

Hence, I feel this adds little value while in practice it increases the complexity of the integration and the codebase. Since we have written the module in a very extensible way, another module could implement this functionality.
